name: APK Builder

on:
  workflow_dispatch:
    inputs:
      jobId:
        required: true
        type: string

      fileName:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Inputs
        run: |
          echo "Job ID: ${{ github.event.inputs.jobId }}"
          echo "File: ${{ github.event.inputs.fileName }}"
