name: APK Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Started
        run: |
          echo "APK Build Started"
          echo "Future Android Build Engine Will Run Here"

      - name: Build Finished
        run: echo "Build Complete"
